In [17]:
import numpy as np
import tensorflow as tf
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [18]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [19]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)


In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [21]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [35]:
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(4,)),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Reshape((16, 4)),
    tf.keras.layers.Conv1D(64, 3, activation='relu', padding='same'),
    tf.keras.layers.MaxPooling1D(2),
    tf.keras.layers.Conv1D(32, 3, activation='relu', padding='same'),
    tf.keras.layers.MaxPooling1D(2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(3, activation='softmax')
])

In [36]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


In [37]:
model.fit(X_train, y_train, epochs=100, batch_size=8, validation_data=(X_test, y_test))


Epoch 1/100
15/15 [==============================] - 5s 50ms/step - loss: 2.0693 - accuracy: 0.3333 - val_loss: 1.0946 - val_accuracy: 0.3667
Epoch 2/100
15/15 [==============================] - 0s 13ms/step - loss: 1.8448 - accuracy: 0.3917 - val_loss: 1.0944 - val_accuracy: 0.3667
Epoch 3/100
15/15 [==============================] - 0s 14ms/step - loss: 2.0071 - accuracy: 0.3417 - val_loss: 1.0931 - val_accuracy: 0.5333
Epoch 4/100
15/15 [==============================] - 0s 12ms/step - loss: 1.9198 - accuracy: 0.3000 - val_loss: 1.0911 - val_accuracy: 0.4000
Epoch 5/100
15/15 [==============================] - 0s 9ms/step - loss: 2.1082 - accuracy: 0.3000 - val_loss: 1.0899 - val_accuracy: 0.4000
Epoch 6/100
15/15 [==============================] - 0s 8ms/step - loss: 1.9126 - accuracy: 0.3333 - val_loss: 1.0911 - val_accuracy: 0.5000
Epoch 7/100
15/15 [==============================] - 0s 9ms/step - loss: 1.7915 - accuracy: 0.3583 - val_loss: 1.0916 - val_accuracy: 0.3667
Epoch 8/1

In [42]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f'\nTest Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}')


1/1 [==============================] - 0s 29ms/step - loss: 0.7423 - accuracy: 0.5333

Test Loss: 0.7423, Test Accuracy: 0.5333


In [43]:
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)

1/1 [==============================] - 0s 22ms/step


In [44]:
y_test_original = label_encoder.inverse_transform(y_test)
y_pred_original = label_encoder.inverse_transform(y_pred_classes)

In [45]:
print("\nClassification Report:")
print(classification_report(y_test_original, y_pred_original))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test_original, y_pred_original))


Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.20      0.33        10
           1       0.39      1.00      0.56         9
           2       1.00      0.45      0.62        11

    accuracy                           0.53        30
   macro avg       0.80      0.55      0.51        30
weighted avg       0.82      0.53      0.51        30


Confusion Matrix:
[[2 8 0]
 [0 9 0]
 [0 6 5]]
